### ISSUE TITLE
jstest complaining about compatibility issues

### ISSUE THREAD

**Issue by jose1711** [adiel-mittmann/dancepad#3]
with "vanilla" `joydev` i am seeing a device with 12 buttons:
```
jstest /dev/input/js0
Driver version is 2.1.0.
Joystick (USB Gamepad ) has 6 axes (X, Y, Z, Rz, Hat0X, Hat0Y)
and 12 buttons (Trigger, ThumbBtn, ThumbBtn2, TopBtn, TopBtn2, PinkieBtn, BaseBtn, BaseBtn2, BaseBtn3, BaseBtn4, BaseBtn5, BaseBtn6).
Testing ... (interrupt to exit)
Axes:  0:     0  1:     0  2:     0  3:     0  4:     0  5:     0 Buttons:  0:off  1:off  2:off  3:off  4:off  5:off  6:off  7:off  8:off  9:off 10:off 11:off 
```

after patching `joydev` (kernel: 5.9.6) I get 4 new buttons but `jstest` starts complaining:
```
❯ jstest /dev/input/js0
Driver version is 2.1.0.
jstest is not fully compatible with your kernel. Unable to retrieve button map!
Joystick (USB Gamepad ) has 6 axes and 16 buttons.
Testing ... (interrupt to exit)
Axes:  0:     0  1:     0  2:     0  3:     0  4:     0  5:     0 Buttons:  0:off  1:off  2:off  3:off  4:off  5:off  6:off  7:off  8:off  9:off 10:off 11:off 12:off 13:off 14:off 15:off 
```
~~Further `stepmania` is unable to pick up new buttons (previously seen as axes). In its log I can see it's reporting 12 seen keys:~~
```
Input device: /dev/input/event22: USB device, ID 0810:0003, version 110: USB Gamepad 
    Event types: syn, key, abs, misc
    Total keys: 12; total axes: 0
```

~~I am still able to map buttons to keys via `qjoypad` but it would be nicer to not have to resort to workarounds.~~

Solved by removing `/dev/input/eventXY` before prior to `stepmania` as mentioned in `README.md`.

**Comment by adiel-mittmann** [comment]
If I understand correctly, I can close the issue, right?

If I'm mistaken, feel free to reopen it.

**Comment by jose1711** [comment]
Well.. I did solve the problem with stepmania. But `jstest` keeps complaining. Not sure if this is something that can be easily fixed or not.
