### ISSUE TITLE
question: a possibility to convert this to dkms?

### ISSUE THREAD

**Issue by jose1711** [adiel-mittmann/dancepad#5]
Since getting the whole kernel source tree takes usually a long time is there a possibility to turn this into dkms package so that only kernel headers are required to be installed?

**Comment by adiel-mittmann** [comment]
Thanks for the suggestion.

I never did try to make this code more than a patch.  I have always thought that there has to be a better way than the current approach, right?

Unfortunately, I don't have time right now.

I will leave this issue open in case I ever get around to improving the patch.  Maybe someone sees it and gets motivated to do it too.

**Comment by jose1711** [comment]
Hmm... this may be easier than I thought. All I need here is kernel headers installed and `joydev.c` + patch downloaded from github. The whole operation takes only couple seconds (mostly due to `depmod`) on my 10y old computer.

```
mkdir joydev
cd joydev

cat > Makefile <<"HERE"
obj-m = joydev.o
KVERSION = $(shell uname -r)

all:
	make -C /lib/modules/$(KVERSION)/build M=$(PWD) modules
clean:
	make -C /lib/modules/$(KVERSION)/build M=$(PWD) clean
HERE

# get the latest joydev source code. 
# if you need a specific version - you can use any tag listed at https://github.com/torvalds/linux/tags
# instead of HEAD
wget -q https://raw.githubusercontent.com/torvalds/linux/HEAD/drivers/input/joydev.c

# get the patch
wget -q https://raw.githubusercontent.com/adiel-mittmann/dancepad/master/joydev-dancepad-1.2-4.13.3.patch

# patch the source
patch -Np3 -i joydev-dancepad-1.2-4.13.3.patch

# edit joydev.c changing DANCEPAD_VENDOR and/or DANCEPAD_PRODUCT if necessary

# build the module and put it in place
make
xz joydev.ko
sudo modprobe -r joydev
sudo cp joydev.ko.xz /lib/modules/`uname -r`/kernel/drivers/input/
sudo depmod
sudo modprobe joydev
```

**Comment by adiel-mittmann** [comment]
I am impressed.  I didn't know things could be this easy!  I will add this to the documentation as soon as possible.

Thanks again.
